
import { ExamConfig, GeneratedFiles } from '../types';

export const generateLatexFiles = (config: ExamConfig): GeneratedFiles => {
  // Generate content for dynamic sections
  const sectionsContent = config.sections.map((section, index) => {
    return `
\\section*{${section.title}}
${section.content}
\\begin{enumerate}
    \\item 题目 ${index + 1}.1 (在这里粘贴题目)
    \\vspace{2cm} % 留白
\\end{enumerate}`;
  }).join('\n');

  // Helper to convert numbers to Chinese numerals (1-20)
  const toChineseNum = (num: number): string => {
    const chars = ['','一','二','三','四','五','六','七','八','九','十'];
    if (num <= 10) return chars[num];
    if (num < 20) return '十' + (num % 10 === 0 ? '' : chars[num % 10]);
    if (num === 20) return '二十';
    return num.toString();
  };

  const qCount = Math.max(1, Math.min(20, config.questionCount || 9));
  const totalCols = qCount + 2; // Label + Questions + Total
  
  // Build header row: 题号 & 一 & 二 ... & 总分 \\
  let headerRow = '题号';
  for (let i = 1; i <= qCount; i++) {
    headerRow += ` & ${toChineseNum(i)}`;
  }
  headerRow += ' & 总分 \\\\';
  
  // Build score and marker rows with empty cells
  let emptyRowContent = '';
  for (let i = 0; i < qCount + 1; i++) {
    emptyRowContent += ' & ';
  }
  const scoreRow = `得分${emptyRowContent}\\\\`;
  const markerRow = `阅卷人${emptyRowContent}\\\\`;


  const clsContent = `
% ---------------------------------------------------------------------
% Exam Class File based on generic university style
% Generated by ExamSmith
% ---------------------------------------------------------------------
\\NeedsTeXFormat{LaTeX2e}
\\ProvidesClass{examtemplate}[2024/05/20 Exam Paper Class]

\\LoadClass[a4paper,11pt]{article}

% --- Packages ---
\\RequirePackage[UTF8]{ctex} % Chinese support
\\RequirePackage{geometry}
\\RequirePackage{amsmath, amssymb}
\\RequirePackage{graphicx}
\\RequirePackage{fancyhdr}
\\RequirePackage{array}
\\RequirePackage{booktabs}
\\RequirePackage{calc}
\\RequirePackage{lastpage}
\\RequirePackage{titlesec}
\\RequirePackage{enumitem}
\\RequirePackage{tabularx} % Required for layout

% --- Page Layout ---
\\geometry{left=2.5cm, right=2.5cm, top=2.0cm, bottom=2.5cm} 

% --- Defined Data Fields ---
\\newcommand{\\@university}{${config.university}}
\\newcommand{\\@schoolyear}{${config.yearRange}}
\\newcommand{\\@semester}{${config.semester}}
\\newcommand{\\@course}{${config.courseName}}
\\newcommand{\\@coursecode}{${config.courseCode}}
\\newcommand{\\@duration}{${config.examDuration}}
\\newcommand{\\@papertype}{${config.paperType}}
\\newcommand{\\@exammode}{${config.examMode}}
\\newcommand{\\@college}{${config.college}}
\\newcommand{\\@major}{${config.major}}

% --- Helper for Underlines ---
% Creates a fixed-width underline for filling in data with BOLD text
\\newcommand{\\fixedunderline}[2]{%
  \\underline{\\makebox[#1][c]{\\bfseries #2}}%
}

% --- Header Construction ---
\\newcommand{\\makeexamheader}{
  \\thispagestyle{plain}
  
  % 1. Top Warning Text
  \\begin{center}
    \\small
    诚信关于个人一生，公平竞争赢得尊重。\\\\
    \\vspace{3pt}
    % \\noindent prevents indentation overflow. 
    % \\resizebox{\\linewidth}{!} scales the content to exactly fit the page width.
    \\noindent\\resizebox{\\linewidth}{!}{\\underline{\\bfseries 以下行为是严重作弊行为，学校将给予留校察看或开除学籍处分：1. 替他人考试或由他人替考；2. 通讯工具作弊；3. 团伙作弊。}}
  \\end{center}
  
  \\vspace{-2em} % Pull title much closer to the warning line above (Reduced whitespace)
  
  % 2. Main Title with Underlines
  \\begin{center}
    \\zihao{3}\\heiti \\@university \\ \\underline{\\@schoolyear} \\ 学年第 \\underline{\\ \\@semester \\ } \\ 学期课程考试试卷 (回忆)
  \\end{center}
  
  \\vspace{-0.5em} % Significantly reduce whitespace below title
  
  % 3. Meta Data Lines (Using tabularx for alignment and equal underline lengths)
  % Adjusted vertical spacing to 0.2cm (Compact)
  % Added hspace{0.5em} to replace colons with whitespace
  
  % Row 1: Subject (Left) and Paper Type (Right). Underlines: 5.5cm
  \\noindent
  \\begin{tabularx}{\\linewidth}{@{} *{2}{>{\\raggedright\\arraybackslash}X} @{}}
    考试科目\\hspace{0.5em}\\fixedunderline{5.5cm}{\\@course} & 试卷类型\\hspace{0.5em}\\fixedunderline{5.5cm}{\\@papertype}
  \\end{tabularx}
  
  \\vspace{0.2cm} % Compact spacing
  
  % Row 2: Code, Duration, Mode. Underlines: 2cm
  \\noindent
  \\begin{tabularx}{\\linewidth}{@{} *{3}{>{\\raggedright\\arraybackslash}X} @{}}
    课程代码\\hspace{0.5em}\\fixedunderline{2cm}{\\@coursecode} & 考试时长\\hspace{0.5em}\\fixedunderline{2cm}{\\@duration} 分钟 & 考试方式\\hspace{0.5em}\\fixedunderline{2cm}{\\@exammode}
  \\end{tabularx}

  \\vspace{0.2cm} % Compact spacing
  
  % Row 3: College, Major. Underlines: 5cm
  \\noindent
  \\begin{tabularx}{\\linewidth}{@{} *{2}{>{\\raggedright\\arraybackslash}X} @{}}
    开课学院\\hspace{0.5em}\\fixedunderline{5cm}{\\@college} & 年级专业\\hspace{0.5em}\\fixedunderline{5cm}{\\@major}
  \\end{tabularx}
  
  \\vspace{0.2cm} % Compact spacing
  
  % Row 4: Student Info. Underlines: 2.2cm
  \\noindent
  \\begin{tabularx}{\\linewidth}{@{} *{4}{>{\\raggedright\\arraybackslash}X} @{}}
    学院\\hspace{0.5em}\\fixedunderline{2.2cm}{} & 班级\\hspace{0.5em}\\fixedunderline{2.2cm}{} & 姓名\\hspace{0.5em}\\fixedunderline{2.2cm}{} & 学号\\hspace{0.5em}\\fixedunderline{2.2cm}{}
  \\end{tabularx}
  
  \\vspace{0.15cm} % Extremely compact spacing before score table
  
  % 5. Score Table
  \\noindent
  {%
  % Increase row height globally for this table to center text vertically without struts
  % Reduced from 2.0 to 1.5 for a "slightly smaller" height
  \\renewcommand{\\arraystretch}{1.5}%
  % Redefine X column to be vertically centered (m) and horizontally centered
  % IMPORTANT: Use ##1 instead of #1 because this command is defined inside another command (\makeexamheader)
  \\renewcommand{\\tabularxcolumn}[1]{>{\\centering\\arraybackslash}m{##1}}%
  % Removed 'center' environment to avoid extra vertical space
  % Dynamically generated columns based on questionCount
  \\begin{tabularx}{\\linewidth}{|*{${totalCols}}{X|}}
    \\hline
    ${headerRow}
    \\hline
    ${scoreRow}
    \\hline
    ${markerRow}
    \\hline
  \\end{tabularx}%
  }
  
  \\vspace{0.2cm} % Reduced spacing between score table and pledge box
  
  % 6. Pledge Box
  \\noindent
  % Thicken the box border
  \\setlength{\\fboxrule}{1.5pt}%
  % Reduce inner padding (was 15pt, then 6pt)
  \\setlength{\\fboxsep}{6pt}%
  \\fbox{%
    \\parbox{\\dimexpr\\linewidth-2\\fboxsep-2\\fboxrule\\relax}{%
      \\linespread{1.1}\\selectfont % Slightly smaller line spacing inside
      \\bfseries % Make all text inside bold
      \\vspace{2pt} % Minimal top spacing
      \\hspace{1em}考生承诺： % Indented title (approx 1 char width)
      % wide=0pt: No hanging indent (lines start at margin)
      % itemsep=0pt: tight spacing
      \\begin{enumerate}[label=\\arabic*., wide=0pt, labelsep=0.5em, topsep=0pt, itemsep=0pt, parsep=0pt]
        \\item 未携带通信工具及其他各类带有拍照、摄像、接收、发送、储存等功能的设备（包括但不限于手机、智能手表、智能眼镜、平板电脑、无线耳机）或关机并将其置于监考老师指定位置；
        \\item 已按要求清理干净整个座位（包括考生邻座）桌面和抽屉里的所有物品（无论是否属于考生本人）；
        \\item 已知晓并理解《${config.university}学生违纪处分管理规定》等与考试相关规定，承诺在考试中自觉遵守以上规定，服从监考教师的安排，自觉遵守考场纪律，诚信考试，不违规、不作弊。如有违反，自愿按《${config.university}学生违纪处分管理规定》相关条款接受处理。
      \\end{enumerate}
      \\vspace{2pt} % Minimal bottom spacing
      \\hfill 考生签名：\\fixedunderline{3cm}{} % Smaller underline (3cm)
      \\vspace{5pt} % Minimal bottom margin for signature
    }%
  }
  \\vspace{0.5cm}
}
`;

  const texContent = `
% ---------------------------------------------------------------------
% Main Tex File
% Compile with XeLaTeX
% ---------------------------------------------------------------------
\\documentclass{examtemplate}

% Put any extra packages here if needed

\\begin{document}

% Generate the cover header
\\makeexamheader

% --- Exam Content Starts Here ---

${sectionsContent || '% No sections defined. Add sections in the configuration tool.'}

\\end{document}
`;

  return {
    cls: clsContent.trim(),
    tex: texContent.trim(),
  };
};
